---
title:    "Data Import and Cleaning"
author:   "Michael Grix"
date:     "06Oct2024"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r includes, message=FALSE}
library(ISLR)
library(ggformula)
library(dplyr)
library(lubridate)
library(ISOweek)
```

```{r import}
raw_data <- read.csv("./RawData/Starting Data.csv", header = TRUE, sep = ",")
```

```{r date handling production}

## Date Handling
assign_days <- function(week_samples, days_to_assign, column_name, year_column, week_column) {
  # Ensure days_to_assign cycles if there are more samples than days provided
  num_samples <- nrow(week_samples)
  assigned_days <- rep_len(days_to_assign, num_samples)  # Repeats days_to_assign if necessary
  
  # Calculate the start of the year for the given year_column
  start_of_year <- ymd(paste0(week_samples[[year_column]][1], "-01-01"))
  
  # Calculate the start of the production week based on the week_column
  week_start_date <- start_of_year + weeks(week_samples[[week_column]][1] - 1)
  
  # Assign final dates
  week_samples[[column_name]] <- week_start_date + days(assigned_days)

  return(week_samples)
}

# Production Dates
raw_data$prod_year <- as.numeric(substr(raw_data$Production.Date, 1, 4))
raw_data$prod_week <- as.numeric(substr(raw_data$Production.Date, 6, 7))

# Apply the assign_days function to production dates
raw_data <- raw_data %>%
  group_by(prod_year, prod_week) %>%
  do(assign_days(., days_to_assign = c(0, 2, 4, 6), column_name = "Prod_date", year_column = "prod_year", week_column = "prod_week"))

# Potency Dates
raw_data$pot_year <- as.numeric(substr(raw_data$Potency.Test.Date, 1, 4))
raw_data$pot_week <- as.numeric(substr(raw_data$Potency.Test.Date, 6, 7))

# Apply the assign_days function to potency test dates
raw_data <- raw_data %>%
  group_by(pot_year, pot_week) %>%
  do(assign_days(., days_to_assign = c(1, 5), column_name = "Potency_date", year_column = "pot_year", week_column = "pot_week"))


write.csv(raw_data, "Clean Data/clean_data.csv", row.names = FALSE)

```



